# Generated by Django 5.2 on 2025-06-21 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('tienda', '0002_alter_pedido_cliente_tienda_publica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('propuesta', 'Propuesta'), ('negociacion', 'Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('probabilidad', models.IntegerField(default=0)),
                ('fuente', models.CharField(choices=[('ecommerce', 'Tienda Online'), ('manual', 'Lead Manual'), ('otro', 'Otro')], default='ecommerce', max_length=50)),
                ('total_compras', models.IntegerField(default=0)),
                ('valor_total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('frecuencia_compra', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'email')},
            },
        ),
        migrations.CreateModel(
            name='InteraccionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunión'), ('compra', 'Compra'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='leads.lead')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
