# Generated by Django 5.2.1 on 2025-06-24 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('backup_type', models.CharField(choices=[('automatic', 'Automático'), ('manual', 'Manual'), ('admin', 'Administrador')], default='manual', max_length=20, verbose_name='Tipo de respaldo')),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='Archivo')),
                ('size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas administrativas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_all_backups', 'Puede gestionar todos los respaldos')],
            },
        ),
    ]
