# Generated by Django 5.2 on 2025-06-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('plan_type', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20, verbose_name='Tipo de Plan')),
                ('duration_months', models.IntegerField(verbose_name='Duración en Meses')),
                ('max_products', models.IntegerField(default=100, verbose_name='Máximo de Productos')),
                ('max_users', models.IntegerField(default=5, verbose_name='Máximo de Usuarios')),
                ('max_storage', models.IntegerField(default=5, verbose_name='Almacenamiento en GB')),
                ('has_crm', models.BooleanField(default=True, verbose_name='Incluye CRM')),
                ('has_ecommerce', models.BooleanField(default=True, verbose_name='Incluye Ecommerce')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Incluye Analytics')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='Acceso a API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('trial', 'Prueba')], default='trial', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de fin')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fin del período de prueba')),
                ('products_count', models.IntegerField(default=0, verbose_name='Número de productos')),
                ('users_count', models.IntegerField(default=0, verbose_name='Número de usuarios')),
                ('storage_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Almacenamiento usado (GB)')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Último pago')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Próximo pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
