# Generated by Django 5.2 on 2025-06-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', models.CharField(default='#3498db', max_length=20, verbose_name='Color Primario')),
                ('color_secundario', models.CharField(default='#2ecc71', max_length=20, verbose_name='Color Secundario')),
                ('color_texto', models.CharField(default='#333333', max_length=20, verbose_name='Color de Texto')),
                ('color_fondo', models.CharField(default='#ffffff', max_length=20, verbose_name='Color de Fondo')),
                ('tipo_fuente', models.CharField(default='Arial', max_length=100, verbose_name='Tipo de Fuente')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10, verbose_name='Tema')),
                ('vista_producto', models.CharField(choices=[('grid', 'Cuadrícula'), ('list', 'Lista')], default='grid', max_length=10, verbose_name='Vista de Producto')),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='tienda.tienda')),
            ],
        ),
    ]
