# Generated by Django 5.2 on 2025-06-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_style', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestyle',
            name='vista_producto',
            field=models.CharField(choices=[('grid', 'Cuadrícula'), ('list', 'Lista'), ('detallada', 'Detallada'), ('masonry', 'Masonry')], default='grid', max_length=10, verbose_name='Vista de Producto'),
        ),
    ]
