# Generated by Django 5.2 on 2025-06-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_style', '0002_alter_storestyle_vista_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestyle',
            name='bloques_bienvenida',
            field=models.JSONField(blank=True, default=list, verbose_name='Bloques de Bienvenida'),
        ),
        migrations.AddField(
            model_name='storestyle',
            name='tema_plantilla',
            field=models.CharField(choices=[('clasico', 'Clásico'), ('urbano', 'Urbano'), ('corporativo', 'Corporativo')], default='clasico', max_length=20, verbose_name='Tema de Plantilla'),
        ),
    ]
