# Generated by Django 5.2 on 2025-06-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_style', '0003_storestyle_bloques_bienvenida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestyle',
            name='bloques_bienvenida',
            field=models.JSONField(blank=True, default=list, help_text='Lista de bloques con campos: tipo, titulo, descripcion, imagen', verbose_name='Bloques de Bienvenida'),
        ),
    ]
