# Generated by Django 5.2 on 2025-06-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_style', '0004_alter_storestyle_bloques_bienvenida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestyle',
            name='bloques_bienvenida',
        ),
        migrations.CreateModel(
            name='BloqueBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('apilado', 'Apilado'), ('en_linea', 'En Línea')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bloques/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='store_style.storestyle')),
            ],
        ),
    ]
