# Generated by Django 5.2 on 2025-06-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTiendaPublica', '0002_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_tienda_publica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_tienda', to='UsersTiendaPublica.userstiendapublica'),
        ),
    ]
