# Generated by Django 5.2.1 on 2025-06-24 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_pedido_cliente_tienda_publica'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
    ]
